### ISSUE TITLE
Build Error - Argument to '-isysroot' is missing

### ISSUE THREAD

**Issue by UmarAbubacar** [BioDynaMo/biodynamo#355]
I encounter a build error while trying to build the src or my project. The error message indicates that an argument to '-isysroot' is missing. Here is the output from the build process:

```
[ 15%] Generating libCortex_3_bdm_dict.cc
[ 15%] Generating libCortex_3_dict.cc, libCortex_3_dict_rdict.pcm
clang: error: argument to '-isysroot' is missing (expected 1 value)
clang: error: no input files
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -isysroot;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk   -xc++ -E -v /dev/null 2>&1 | sed -n -e '/^.include/,${' -e '/^ \/.*++/p' -e '}'
Results was:
clang: error: argument to '-isysroot' is missing (expected 1 value)
clang: error: no input files
With exit code 0
```
My environment is:
Xcode version: 15.2
MacOS 14.2.1

There is this similar issue on the ROOT forum: https://root-forum.cern.ch/t/issues-with-root-after-the-developer-tools-apdate/56410 

Could this be resolved with an updated ROOT version for the newer Xcode?

**Comment by TobiasDuswald** [comment]
I think Fons recently built it for Xcode 15.0 (https://github.com/BioDynaMo/biodynamo/issues/352#issuecomment-1826749156, https://github.com/BioDynaMo/biodynamo/issues/352#issuecomment-1829926260), which I believe/hope should work on XCode 15.x.

Can you investigate if the right XCode is downloaded and check if it works? see explanation in #352.

**Comment by UmarAbubacar** [comment]
I have tried all the steps with reinstalling Xcode and command line tools but I get the same `-isysroot` error for Xcode 15.2. 

PS. There is no version of paraview for MacOS 14.2 but I have been using paraview for 14.1 in the branch `umar_neurite_test`. I don't think this is related to the issue however.

**Comment by FonsRademakers** [comment]
Hi,

 please try again, master should work now on macOS 14.2 with Xcode 15.2. Please port the file cmake/external/SHA256Digests.cmake from master to umar_neurite_test.

Cheers, Fons.


> On Jan 17, 2024, at 15:07, Umar ***@***.***> wrote:
> 
> 
> I have tried all the steps with reinstalling Xcode and command line tools but I get the same -isysroot error for Xcode 15.2.
> PS. There is no version of paraview for MacOS 14.2 but I have been using paraview for 14.1 in the branch umar_neurite_test. I don't think this is related to the issue however.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

--
Dr. Fons Rademakers
Senior Scientist
CERN - European Organization for Nuclear Research

**Comment by UmarAbubacar** [comment]
Thank you @FonsRademakers the master branch works now for installing paraview, however I still get the same`-isysroot ` error. I can confirm its using the SHA:
osx-xcode-15.0.1-arm64-ROOT de60b679f09e7ccde3f5d117e728ffb28d705196935ada5b29f5cc27f2c03091

**Comment by FonsRademakers** [comment]
Yes, I also get these errors in my built, but the unit-tests work fine. It is related to an issue with the ROOT cling C++ interpreter. This is fixed in the new ROOT 6.30.02 but that requires we update to C++17. I will see if that works with BioDynaMo.

Cheers, Fons.




> On Jan 17, 2024, at 17:16, Umar ***@***.***> wrote:
> 
> 
> Thank you @FonsRademakers the master branch works now for installing paraview, however I still get the same-isysroot error. I can confirm its using the SHA:
> osx-xcode-15.0.1-arm64-ROOT de60b679f09e7ccde3f5d117e728ffb28d705196935ada5b29f5cc27f2c03091
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

--
Dr. Fons Rademakers
Senior Scientist
CERN - European Organization for Nuclear Research

**Comment by UmarAbubacar** [comment]
Okay no worries, thank you for the update. Should I leave this issue open for the time being as a reference?

**Comment by TobiasDuswald** [comment]
Discussion related to ROOT v6.30.02 and BDM on C++17 continues in #356 .
